/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://www.netbeans.org/cddl.html
 * or http://www.netbeans.org/cddl.txt.
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://www.netbeans.org/cddl.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 *
 * The Original Software is NetBeans. The Initial Developer of the Original
 * Software is Sun Microsystems, Inc. Portions Copyright 1997-2007 Sun
 * Microsystems, Inc. All Rights Reserved.
 */
package org.netbeans.modules.web.frameworks.struts2.ui;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.netbeans.api.project.libraries.Library;
import org.netbeans.api.project.libraries.LibraryManager;
import org.netbeans.modules.web.frameworks.struts2.ConfigUtilities;
import org.openide.util.Exceptions;

/**
 *
 * @author  Petr Pisl, Rohan Ranade
 */
public class FrameworkSetupPanelVisual extends javax.swing.JPanel {

    /** The default library, which will be selected.
     */
    private static final String STRUTS2_DEFAULT_LIBRARY = "struts2lib-2-2-3-core";
    private FrameworkSetupPanel frameworkSetup;
    private ArrayList<Library> strutsLibraries;

    /** Creates new form FrameworkSetupPanel */
    public FrameworkSetupPanelVisual(FrameworkSetupPanel frameworkSetup) {
        this.frameworkSetup = frameworkSetup;
        initComponents();
        pLibraries.setVisible(!frameworkSetup.customizer);
        if (!frameworkSetup.customizer) {
            initLibraries();
        }
    }

    private void initLibraries() {

        List<String> items = new ArrayList<String>();
        strutsLibraries = new ArrayList<Library>();
        Library defaultLibrary = null;
        try {
            Library[] registeredLibraries = LibraryManager.getDefault().getLibraries();
            Library[] struts2Libs = ConfigUtilities.filterStruts2Libraries(registeredLibraries);
            for (Library library : struts2Libs) {
                items.add(library.getDisplayName());
                strutsLibraries.add(library);
                if (STRUTS2_DEFAULT_LIBRARY.equals(library.getName()) || defaultLibrary == null) {
                    defaultLibrary = library;
                }
            }
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }

        cbLibraries.setModel(new DefaultComboBoxModel(items.toArray(new String[items.size()])));
        if (items.isEmpty()) {
            rbRegisteredLirary.setEnabled(false);
            cbLibraries.setEnabled(false);
            rbNoneLibrary.setSelected(true);
            frameworkSetup.setSelectedLibrary(null);
        } else {
            rbRegisteredLirary.setEnabled(true);
            rbRegisteredLirary.setSelected(true);
            cbLibraries.setEnabled(true);
            cbLibraries.setSelectedItem(defaultLibrary.getDisplayName());
            frameworkSetup.setSelectedLibrary(defaultLibrary);
        }
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLibrary = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pConfiguration = new javax.swing.JPanel();
        cbExample = new javax.swing.JCheckBox();
        pLibraries = new javax.swing.JPanel();
        cbLibraries = new javax.swing.JComboBox();
        rbRegisteredLirary = new javax.swing.JRadioButton();
        rbNoneLibrary = new javax.swing.JRadioButton();

        cbExample.setSelected(true);
        cbExample.setText(org.openide.util.NbBundle.getMessage(FrameworkSetupPanelVisual.class, "LBL_CREATE_EXAMPLE")); // NOI18N
        cbExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExampleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pConfigurationLayout = new javax.swing.GroupLayout(pConfiguration);
        pConfiguration.setLayout(pConfigurationLayout);
        pConfigurationLayout.setHorizontalGroup(
            pConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfigurationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbExample, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );
        pConfigurationLayout.setVerticalGroup(
            pConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConfigurationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbExample)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/netbeans/modules/web/frameworks/struts2/ui/properties"); // NOI18N
        jTabbedPane1.addTab(bundle.getString("TAB_CONFIGURATION"), pConfiguration); // NOI18N

        cbLibraries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLibraries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLibrariesActionPerformed(evt);
            }
        });

        bgLibrary.add(rbRegisteredLirary);
        rbRegisteredLirary.setText(bundle.getString("LBL_REGISTERED_LIB")); // NOI18N
        rbRegisteredLirary.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbRegisteredLirary.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbRegisteredLirary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRegisteredLiraryActionPerformed(evt);
            }
        });

        bgLibrary.add(rbNoneLibrary);
        rbNoneLibrary.setText(bundle.getString("LBL_NONE")); // NOI18N
        rbNoneLibrary.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbNoneLibrary.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rbNoneLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoneLibraryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLibrariesLayout = new javax.swing.GroupLayout(pLibraries);
        pLibraries.setLayout(pLibrariesLayout);
        pLibrariesLayout.setHorizontalGroup(
            pLibrariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLibrariesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLibrariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pLibrariesLayout.createSequentialGroup()
                        .addComponent(rbRegisteredLirary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbLibraries, 0, 189, Short.MAX_VALUE))
                    .addComponent(rbNoneLibrary))
                .addContainerGap())
        );
        pLibrariesLayout.setVerticalGroup(
            pLibrariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLibrariesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pLibrariesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRegisteredLirary)
                    .addComponent(cbLibraries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbNoneLibrary)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(bundle.getString("TAB_LIBRARIES"), pLibraries); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbLibrariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLibrariesActionPerformed
        frameworkSetup.setSelectedLibrary(strutsLibraries.get(cbLibraries.getSelectedIndex()));
    }//GEN-LAST:event_cbLibrariesActionPerformed

    private void rbRegisteredLiraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRegisteredLiraryActionPerformed
        frameworkSetup.setSelectedLibrary(strutsLibraries.get(cbLibraries.getSelectedIndex()));
    }//GEN-LAST:event_rbRegisteredLiraryActionPerformed

    private void rbNoneLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoneLibraryActionPerformed
        frameworkSetup.setSelectedLibrary(null);
    }//GEN-LAST:event_rbNoneLibraryActionPerformed

    private void cbExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExampleActionPerformed
        frameworkSetup.setIsExampleRequired(cbExample.isSelected());
    }//GEN-LAST:event_cbExampleActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLibrary;
    private javax.swing.JCheckBox cbExample;
    private javax.swing.JComboBox cbLibraries;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pConfiguration;
    private javax.swing.JPanel pLibraries;
    private javax.swing.JRadioButton rbNoneLibrary;
    private javax.swing.JRadioButton rbRegisteredLirary;
    // End of variables declaration//GEN-END:variables
}
